import { Artwork } from "@/types/artwork";

export const artworks: Artwork[] = [
  {
    id: "ak-001",
    title: "Redemption Song I",
    year: 2006,
    medium: "Oil on canvas",
    dimensions: "120 × 160 cm",
    src: "/images/placeholder/artwork-1.svg",
    alt: "Redemption Song I",
    featured: true,
  },
  {
    id: "ak-002",
    title: "The Rembrandt-Lounge",
    year: 1993,
    medium: "Mixed media installation",
    dimensions: "Variable dimensions",
    src: "/images/placeholder/artwork-2.svg",
    alt: "The Rembrandt-Lounge",
    featured: true,
  },
  {
    id: "ak-003",
    title: "Los Desastres de la Guerra",
    year: 1993,
    medium: "Ink on paper",
    dimensions: "70 × 100 cm",
    src: "/images/placeholder/artwork-3.svg",
    alt: "Los Desastres de la Guerra",
    featured: true,
  },
  {
    id: "ak-004",
    title: "Gobelin #9",
    year: 2010,
    medium: "Textile, mixed media",
    dimensions: "200 × 300 cm",
    src: "/images/placeholder/artwork-4.svg",
    alt: "Gobelin #9",
    featured: true,
  },
  {
    id: "ak-005",
    title: "Microspektive",
    year: 2007,
    medium: "Photography, text",
    dimensions: "60 × 80 cm",
    src: "/images/placeholder/artwork-5.svg",
    alt: "Microspektive (a brief history of time)",
  },
  {
    id: "ak-006",
    title: "Fin de siècle / New Age",
    year: 1995,
    medium: "Oil on linen",
    dimensions: "90 × 110 cm",
    src: "/images/placeholder/artwork-6.svg",
    alt: "Fin de siècle / New Age",
  },
  {
    id: "ak-007",
    title: "Sättigung",
    year: 2011,
    medium: "Acrylic and graphite on canvas",
    dimensions: "100 × 130 cm",
    src: "/images/placeholder/artwork-7.svg",
    alt: "Sättigung",
  },
  {
    id: "ak-008",
    title: "Four Rivers",
    year: 2005,
    medium: "Landscape intervention, documentation",
    dimensions: "Variable dimensions",
    src: "/images/placeholder/artwork-8.svg",
    alt: "Four Rivers landscape project",
  },
  {
    id: "ak-009",
    title: "Retrozession",
    year: 2002,
    medium: "Installation",
    dimensions: "Variable dimensions",
    src: "/images/placeholder/artwork-9.svg",
    alt: "Retrozession",
  },
  {
    id: "ak-010",
    title: "Kontinental Shift",
    year: 2006,
    medium: "Mixed media",
    dimensions: "150 × 200 cm",
    src: "/images/placeholder/artwork-10.svg",
    alt: "Kontinental Shift",
  },
  {
    id: "ak-011",
    title: "Satellite",
    year: 2008,
    medium: "Light installation",
    dimensions: "Site-specific",
    src: "/images/placeholder/artwork-11.svg",
    alt: "Satellite light installation",
  },
  {
    id: "ak-012",
    title: "Von Anfang an",
    year: 2013,
    medium: "Oil and wax on canvas",
    dimensions: "80 × 100 cm",
    src: "/images/placeholder/artwork-12.svg",
    alt: "Von Anfang an",
  },
];
